import PDFDocument from 'pdfkit';

interface YearProjection {
  year: number;
  guaranteed_amount: number;
  projected_revenue: number;
  profit_share_amount: number;
  total_to_client: number;
}

interface ScoringItem {
  criterion: string;
  max_points: number;
  estimated_points: number;
  justification: string;
}

interface ProposalData {
  rfpTitle: string;
  clientName: string;
  version: number;
  predictedScore: number | null;
  executiveSummary: string | null;
  companyOverview: string | null;
  experienceSection: string | null;
  approachSection: string | null;
  projectTimeline: string | null;
  teamStructure: string | null;
  revenueProposal: string | null;
  costOverview: string | null;
  riskMitigation: string | null;
  valueProposition: string | null;
  complianceStatement: string | null;
  competitiveAdvantages: string | null;
  termsAndConditions: string | null;
  recommendedFlatGuarantee: number | null;
  recommendedProfitShare: number | null;
  annualEscalationPct: number | null;
  yearWiseProjections: YearProjection[] | null;
  scoringBreakdown: ScoringItem[] | null;
  revenueModelRationale: string | null;
  optimizationNotes: string | null;
  createdAt: string;
}

function addHeader(doc: PDFDocument, title: string) {
  doc.addPage();
  doc.fillColor('#1e40af').fontSize(18).font('Helvetica-Bold').text(title, { underline: false });
  doc.moveTo(doc.x, doc.y + 2).lineTo(doc.page.width - doc.page.margins.right, doc.y + 2).strokeColor('#1e40af').lineWidth(2).stroke();
  doc.moveDown(0.8);
  doc.fillColor('#1f2937').font('Helvetica').fontSize(11);
}

function addSubHeader(doc: PDFDocument, title: string) {
  doc.moveDown(0.5);
  doc.fillColor('#1e40af').fontSize(13).font('Helvetica-Bold').text(title);
  doc.moveDown(0.3);
  doc.fillColor('#1f2937').font('Helvetica').fontSize(11);
}

function addBody(doc: PDFDocument, text: string | null) {
  if (!text) return;
  doc.fillColor('#374151').fontSize(10.5).font('Helvetica').text(text, { align: 'justify', lineGap: 3 });
  doc.moveDown(0.5);
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(amount);
}

export function generateProposalPdf(data: ProposalData): PDFDocument {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 60, bottom: 60, left: 55, right: 55 },
    info: {
      Title: `Proposal - ${data.rfpTitle}`,
      Author: 'RFP Proposal AI',
    },
    bufferPages: true,
  });

  // ─── COVER PAGE ───
  doc.rect(0, 0, doc.page.width, doc.page.height).fill('#0f172a');

  doc.fillColor('#ffffff').fontSize(12).font('Helvetica').text('CONFIDENTIAL', 55, 60, { align: 'right' });

  doc.fillColor('#3b82f6').fontSize(14).font('Helvetica').text('PROPOSAL DOCUMENT', 55, 200, { align: 'center' });
  doc.moveDown(0.5);
  doc.fillColor('#ffffff').fontSize(28).font('Helvetica-Bold').text(data.rfpTitle, { align: 'center' });
  doc.moveDown(1);

  doc.fillColor('#94a3b8').fontSize(13).font('Helvetica').text(`Prepared for: ${data.clientName}`, { align: 'center' });
  doc.moveDown(0.5);
  doc.text(`Version ${data.version}`, { align: 'center' });
  doc.moveDown(0.5);
  doc.text(`Date: ${new Date(data.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' });

  if (data.predictedScore) {
    doc.moveDown(2);
    doc.fillColor('#3b82f6').fontSize(16).font('Helvetica-Bold').text(`Predicted Score: ${Number(data.predictedScore).toFixed(1)} / 100`, { align: 'center' });
  }

  // Financial highlights on cover
  doc.moveDown(2);
  doc.fillColor('#94a3b8').fontSize(11).font('Helvetica').text('─────────── Financial Highlights ───────────', { align: 'center' });
  doc.moveDown(0.5);
  if (data.recommendedFlatGuarantee) {
    doc.fillColor('#ffffff').fontSize(12).text(`Minimum Annual Guarantee: ${formatCurrency(data.recommendedFlatGuarantee)}`, { align: 'center' });
  }
  if (data.recommendedProfitShare) {
    doc.text(`Revenue Share: ${Number(data.recommendedProfitShare)}%`, { align: 'center' });
  }
  if (data.annualEscalationPct) {
    doc.text(`Annual Escalation: ${Number(data.annualEscalationPct)}%`, { align: 'center' });
  }

  doc.fillColor('#475569').fontSize(9).text('Generated by RFP Proposal AI', 55, doc.page.height - 80, { align: 'center' });

  // ─── TABLE OF CONTENTS ───
  addHeader(doc, 'Table of Contents');
  const tocItems = [
    '1. Executive Summary',
    '2. Company Overview',
    '3. Experience & Track Record',
    '4. Technical Approach & Methodology',
    '5. Project Timeline & Milestones',
    '6. Team Structure & Key Personnel',
    '7. Financial Proposal & Revenue Model',
    '8. Cost Overview & Breakdown',
    '9. Year-Wise Financial Projections',
    '10. Scoring Strategy & Breakdown',
    '11. Risk Mitigation Plan',
    '12. Value Proposition',
    '13. Competitive Advantages',
    '14. Compliance Statement',
    '15. Terms & Conditions',
  ];
  tocItems.forEach(item => {
    doc.fillColor('#1f2937').fontSize(11).font('Helvetica').text(item, { indent: 20 });
    doc.moveDown(0.3);
  });

  // ─── 1. EXECUTIVE SUMMARY ───
  addHeader(doc, '1. Executive Summary');
  addBody(doc, data.executiveSummary);

  // ─── 2. COMPANY OVERVIEW ───
  addHeader(doc, '2. Company Overview');
  addBody(doc, data.companyOverview);

  // ─── 3. EXPERIENCE ───
  addHeader(doc, '3. Experience & Track Record');
  addBody(doc, data.experienceSection);

  // ─── 4. APPROACH ───
  addHeader(doc, '4. Technical Approach & Methodology');
  addBody(doc, data.approachSection);

  // ─── 5. TIMELINE ───
  addHeader(doc, '5. Project Timeline & Milestones');
  addBody(doc, data.projectTimeline);

  // ─── 6. TEAM ───
  addHeader(doc, '6. Team Structure & Key Personnel');
  addBody(doc, data.teamStructure);

  // ─── 7. FINANCIAL PROPOSAL ───
  addHeader(doc, '7. Financial Proposal & Revenue Model');

  addSubHeader(doc, 'Revenue Model Summary');
  if (data.recommendedFlatGuarantee) {
    doc.font('Helvetica-Bold').fillColor('#059669').fontSize(12)
      .text(`Minimum Annual Guarantee (MAG): ${formatCurrency(data.recommendedFlatGuarantee)}`);
  }
  if (data.recommendedProfitShare) {
    doc.text(`Revenue Share: ${Number(data.recommendedProfitShare)}% of gross revenue above MAG`);
  }
  if (data.annualEscalationPct) {
    doc.text(`Annual Escalation: ${Number(data.annualEscalationPct)}% year-over-year increase in MAG`);
  }
  doc.moveDown(0.5);
  doc.fillColor('#374151').font('Helvetica').fontSize(10.5);

  addSubHeader(doc, 'Revenue Model Rationale');
  addBody(doc, data.revenueModelRationale);

  addSubHeader(doc, 'Detailed Financial Proposal');
  addBody(doc, data.revenueProposal);

  // ─── 8. COST OVERVIEW ───
  addHeader(doc, '8. Cost Overview & Breakdown');
  addBody(doc, data.costOverview);

  // ─── 9. YEAR-WISE PROJECTIONS ───
  addHeader(doc, '9. Year-Wise Financial Projections');

  if (data.yearWiseProjections && data.yearWiseProjections.length > 0) {
    const projections = data.yearWiseProjections as YearProjection[];
    const colWidths = [50, 100, 100, 100, 100];
    const tableX = 55;
    let tableY = doc.y + 5;

    // Table header
    doc.fillColor('#1e40af').font('Helvetica-Bold').fontSize(9);
    const headers = ['Year', 'Guarantee', 'Projected Rev', 'Profit Share', 'Total to Client'];
    headers.forEach((h, i) => {
      const x = tableX + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
      doc.text(h, x, tableY, { width: colWidths[i], align: 'center' });
    });

    tableY += 18;
    doc.moveTo(tableX, tableY).lineTo(tableX + colWidths.reduce((a, b) => a + b, 0), tableY).strokeColor('#cbd5e1').lineWidth(1).stroke();
    tableY += 5;

    // Table rows
    doc.fillColor('#374151').font('Helvetica').fontSize(9);
    let totalGuarantee = 0;
    let totalRevenue = 0;
    let totalShare = 0;
    let totalClient = 0;

    projections.forEach((row) => {
      if (tableY > doc.page.height - 100) {
        doc.addPage();
        tableY = 60;
      }
      const vals = [
        `Year ${row.year}`,
        formatCurrency(row.guaranteed_amount),
        formatCurrency(row.projected_revenue),
        formatCurrency(row.profit_share_amount),
        formatCurrency(row.total_to_client),
      ];
      vals.forEach((v, i) => {
        const x = tableX + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
        doc.text(v, x, tableY, { width: colWidths[i], align: 'center' });
      });
      totalGuarantee += row.guaranteed_amount;
      totalRevenue += row.projected_revenue;
      totalShare += row.profit_share_amount;
      totalClient += row.total_to_client;
      tableY += 18;
    });

    // Total row
    tableY += 2;
    doc.moveTo(tableX, tableY).lineTo(tableX + colWidths.reduce((a, b) => a + b, 0), tableY).strokeColor('#1e40af').lineWidth(1.5).stroke();
    tableY += 5;
    doc.font('Helvetica-Bold').fillColor('#1e40af');
    const totals = ['TOTAL', formatCurrency(totalGuarantee), formatCurrency(totalRevenue), formatCurrency(totalShare), formatCurrency(totalClient)];
    totals.forEach((v, i) => {
      const x = tableX + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
      doc.text(v, x, tableY, { width: colWidths[i], align: 'center' });
    });

    doc.y = tableY + 30;
    doc.fillColor('#374151').font('Helvetica').fontSize(10.5);
  }

  // ─── 10. SCORING BREAKDOWN ───
  addHeader(doc, '10. Scoring Strategy & Breakdown');

  if (data.scoringBreakdown && (data.scoringBreakdown as ScoringItem[]).length > 0) {
    const scoring = data.scoringBreakdown as ScoringItem[];
    scoring.forEach((item) => {
      doc.font('Helvetica-Bold').fillColor('#1e40af').fontSize(11)
        .text(`${item.criterion}: ${item.estimated_points} / ${item.max_points} points`);
      doc.font('Helvetica').fillColor('#374151').fontSize(10)
        .text(item.justification, { indent: 15 });
      doc.moveDown(0.5);
    });

    doc.moveDown(0.5);
    const totalEstimated = scoring.reduce((sum, s) => sum + s.estimated_points, 0);
    const totalMax = scoring.reduce((sum, s) => sum + s.max_points, 0);
    doc.font('Helvetica-Bold').fillColor('#059669').fontSize(13)
      .text(`Total Predicted Score: ${totalEstimated} / ${totalMax}`);
  }

  addSubHeader(doc, 'Optimization Strategy');
  addBody(doc, data.optimizationNotes);

  // ─── 11. RISK MITIGATION ───
  addHeader(doc, '11. Risk Mitigation Plan');
  addBody(doc, data.riskMitigation);

  // ─── 12. VALUE PROPOSITION ───
  addHeader(doc, '12. Value Proposition');
  addBody(doc, data.valueProposition);

  // ─── 13. COMPETITIVE ADVANTAGES ───
  addHeader(doc, '13. Competitive Advantages');
  addBody(doc, data.competitiveAdvantages);

  // ─── 14. COMPLIANCE ───
  addHeader(doc, '14. Compliance Statement');
  addBody(doc, data.complianceStatement);

  // ─── 15. TERMS & CONDITIONS ───
  addHeader(doc, '15. Terms & Conditions');
  addBody(doc, data.termsAndConditions);

  // ─── FOOTER ON ALL PAGES ───
  const pages = doc.bufferedPageRange();
  for (let i = 1; i < pages.start + pages.count; i++) {
    doc.switchToPage(i);
    doc.fillColor('#9ca3af').fontSize(8).font('Helvetica')
      .text(`Confidential | ${data.rfpTitle} | Page ${i + 1}`, 55, doc.page.height - 40, { align: 'center', width: doc.page.width - 110 });
  }

  doc.end();
  return doc;
}
