import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Clean existing data (in reverse dependency order)
  await prisma.proposal.deleteMany();
  await prisma.rfpCompetitor.deleteMany();
  await prisma.scoringCriteria.deleteMany();
  await prisma.rfp.deleteMany();
  await prisma.historicalBid.deleteMany();
  await prisma.competitor.deleteMany();
  await prisma.user.deleteMany();

  // ─── USERS ───
  const passwordHash = await bcrypt.hash('demo123456', 10);
  const user1 = await prisma.user.create({
    data: { email: 'demo@rfpai.com', passwordHash, name: 'Dharmaraj M', role: 'manager' },
  });
  const user2 = await prisma.user.create({
    data: { email: 'suganya@rfpai.com', passwordHash, name: 'Suganya T', role: 'analyst' },
  });
  const user3 = await prisma.user.create({
    data: { email: 'sathish@rfpai.com', passwordHash, name: 'Sathish T', role: 'analyst' },
  });

  console.log(`Created 3 users`);

  // ─── COMPANY PROFILE ───
  await prisma.companyProfile.deleteMany();
  await prisma.companyProfile.create({
    data: {
      companyName: 'Nexus Infrastructure Solutions Pvt Ltd',
      tagline: 'Building India\'s future with innovation, technology, and unwavering commitment to excellence',
      foundedYear: 2008,
      headquarters: 'Mumbai, Maharashtra, India',
      employeeCount: 5200,
      annualRevenue: 'INR 2,800 Crores ($336M USD) - FY 2025',
      industries: ['airport', 'construction', 'logistics', 'healthcare', 'smart-city', 'government', 'renewable-energy', 'retail', 'education', 'port', 'pollution-control', 'steel'],
      certifications: [
        'ISO 9001:2015 (Quality Management)',
        'ISO 14001:2015 (Environmental Management)',
        'ISO 45001:2018 (Occupational Health & Safety)',
        'ISO 27001:2022 (Information Security)',
        'CMMI Level 3',
        'LEED AP Certified Team',
        'HIPAA Compliant',
        'BIS Certified (Solar Modules)',
      ],
      awards: [
        'Best Infrastructure Company - India Infrastructure Awards 2025',
        'Digital Transformation Leader - CII Technology Summit 2024',
        'Green Builder Excellence Award 2024',
        'Smart City Implementation Award - NASSCOM 2024',
        'Best Employer in Infrastructure - Great Place to Work 2025',
      ],
      keyClients: [
        'Airports Authority of India (AAI)',
        'Mumbai International Airport Ltd (MIAL)',
        'Flipkart Internet Pvt Ltd',
        'Fortis Healthcare',
        'Pune Smart City Development Corp',
        'NHAI',
        'CPWD',
        'Indore Smart City',
        'Deendayal Port Authority',
        'Avenue Supermarts (DMart)',
        'BITS Pilani',
        'Karnataka Renewable Energy Dev Ltd',
      ],
      officeLocations: [
        'Mumbai (HQ)',
        'New Delhi',
        'Bangalore',
        'Chennai',
        'Hyderabad',
        'Pune',
        'Ahmedabad',
        'Kolkata',
        'Jaipur',
        'Kochi',
      ],
      safetyRecord: 'Zero fatalities across 18 years of operation. LTIFR of 0.08 (industry best-in-class). 12 consecutive years of zero lost-time incidents on airport projects. ISO 45001 certified since 2018. Dedicated HSE team of 120 professionals.',
      insuranceCoverage: 'Professional Indemnity: $50M. General Liability: $25M. Performance Bond capacity: $200M. Comprehensive All-Risk Insurance on all active projects. Workers Compensation as per statutory requirements.',
      keyMetrics: {
        total_projects_completed: 185,
        projects_delivered_on_time_pct: 94,
        active_projects: 28,
        airports_served: 8,
        hospitals_digitized: 12,
        smart_city_iccc_deployed: 3,
        solar_mw_commissioned: 400,
        warehouse_sqft_managed: 4000000,
        retail_stores_managed: 180,
        port_cargo_mmt_handled: 12.5,
        campus_networks_deployed: 4,
        digital_screens_installed: 1055,
        iot_sensors_deployed: 6550,
        avg_client_satisfaction_score: 4.5,
        client_retention_rate_pct: 92,
        avg_project_cost_variance_pct: 2.8,
        total_workforce_capacity: 8500,
        technology_investment_annual_usd: 12000000,
        esp_installations_completed: 45,
        esp_total_gas_volume_handled_million_m3_hr: 38.5,
        esp_avg_outlet_emission_mg_nm3: 19.8,
        esp_avg_collection_efficiency_pct: 99.3,
        esp_steel_sector_installations: 18,
        esp_sinter_plant_installations: 8,
        esp_pgt_first_pass_rate_pct: 96,
        esp_zero_safety_incident_projects: 42,
        esp_avg_energy_savings_vs_conventional_pct: 22,
      },
      slaDefaults: {
        system_uptime_pct: 99.9,
        incident_response_time_minutes: 15,
        critical_issue_resolution_hours: 4,
        preventive_maintenance_compliance_pct: 96,
        display_uptime_pct: 99.7,
        network_availability_pct: 99.95,
        energy_savings_guarantee_pct: 15,
        report_delivery_within_hours: 24,
        dedicated_support_coverage: '24x7x365',
        escalation_matrix_levels: 4,
      },
      differentiators: {
        ai_powered_analytics: 'Proprietary AI platform processing 8.5M+ data points daily for predictive maintenance, content optimization, and operational intelligence',
        multi_industry_expertise: 'Proven track record across 10 industries with 185+ projects, enabling cross-pollination of best practices',
        end_to_end_capability: 'Full lifecycle services from design and construction to technology integration and long-term O&M',
        digital_twin_technology: 'Digital twin implementations for real-time asset monitoring, reducing unplanned downtime by 35%',
        green_commitment: 'LEED AP certified team, 32% average energy savings delivered across projects, carbon-neutral operations target by 2028',
        rapid_mobilization: 'Ability to deploy teams across India within 2 weeks through 10 regional offices and 5,200+ employee base',
        financial_strength: 'Net worth INR 850 Crores, Debt-Equity ratio 0.4:1, AA- credit rating by CRISIL',
      },
    },
  });

  console.log('Created company profile');

  // ─── COMPETITORS ───
  const competitors = await Promise.all([
    prisma.competitor.create({
      data: {
        name: 'AdVision Global',
        industries: ['airport', 'transit', 'retail', 'hospitality'],
        strengths: 'Strong global presence across 45 airports, extensive advertising portfolio, 18+ years experience, premium brand relationships with Fortune 500 clients',
        weaknesses: 'Higher pricing (15-20% above market), slower response times, rigid contract terms, limited digital innovation',
        typicalBidStyle: 'Premium pricing with extensive service guarantees. Usually offers 8-12% profit share with high flat guarantees. Focuses heavily on experience section.',
        notes: 'Won 3 of last 5 major airport bids in India. CEO has personal connections with AAI leadership.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'MediaReach Corp',
        industries: ['airport', 'healthcare', 'government', 'smart-city'],
        strengths: 'Innovative digital solutions, proprietary AdTech platform with real-time analytics, competitive pricing, strong R&D team',
        weaknesses: 'Limited experience in smaller airports, fewer physical installations, startup culture with occasional delivery delays',
        typicalBidStyle: 'Technology-focused proposals with moderate guarantees. Usually 10-15% profit share with moderate flat amounts. Wins on innovation scores.',
        notes: 'Recently raised $50M Series C. Expanding aggressively into airport vertical.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'BuildMax Construction',
        industries: ['construction', 'government', 'infrastructure', 'real-estate'],
        strengths: 'Lowest cost provider in the market, massive workforce of 5000+, fast execution timelines, strong government relationships',
        weaknesses: 'Quality concerns flagged in 2 past audits, limited innovation capability, high staff turnover (35% annual)',
        typicalBidStyle: 'Aggressive low-ball pricing to win on cost. Minimal profit share (3-5%), lowest possible guarantees. Rarely invests in proposal quality.',
        notes: 'Under investigation for bid rigging in 2023. Cleared but reputation damaged.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'SkyMedia Partners',
        industries: ['airport', 'aviation', 'luxury-retail'],
        strengths: 'Exclusive partnerships with luxury brands, premium content network, excellent design team, strong in international airports',
        weaknesses: 'Very expensive, limited presence in India (mainly Europe/Middle East), small team for large projects',
        typicalBidStyle: 'High-value, design-forward proposals. Premium guarantees with 12-18% revenue share. Positions as luxury/premium partner.',
        notes: 'Entering Indian market for the first time. May bid aggressively to establish presence.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'Vortex Logistics Solutions',
        industries: ['logistics', 'supply-chain', 'warehouse', 'port'],
        strengths: 'Deep supply chain expertise, AI-powered route optimization, nationwide warehouse network, ISO 9001 certified',
        weaknesses: 'No advertising experience, new to media/advertising RFPs, limited creative capability',
        typicalBidStyle: 'Data-driven proposals heavy on operational efficiency. Competitive pricing with emphasis on technology and automation.',
        notes: 'Diversifying from pure logistics into facility management and advertising.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'InfraCore Builders',
        industries: ['construction', 'infrastructure', 'government', 'defense'],
        strengths: 'Tier-1 government contractor, excellent safety record, large bonding capacity ($500M+), 25 years track record',
        weaknesses: 'Bureaucratic internal processes, overcommitted on current projects, not innovative',
        typicalBidStyle: 'Conservative, well-documented proposals. Mid-range pricing. Wins on safety record and government experience.',
        notes: 'Currently managing 3 highway projects and 2 bridge constructions.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'GreenBuild Sustainable',
        industries: ['construction', 'green-energy', 'smart-city', 'government'],
        strengths: 'LEED certification expertise, strong sustainability credentials, growing ESG-focused client base, innovative materials',
        weaknesses: 'Higher costs due to sustainable materials (10-15% premium), smaller scale, limited heavy infrastructure experience',
        typicalBidStyle: 'Sustainability-focused proposals that score high on green/CSR criteria. Moderate pricing with emphasis on long-term value.',
        notes: 'Won "Green Builder of the Year 2025" award. Gaining traction with government ESG mandates.',
      },
    }),
    // ─── NEW COMPETITORS ───
    prisma.competitor.create({
      data: {
        name: 'TechSphere Solutions',
        industries: ['healthcare', 'government', 'education', 'smart-city'],
        strengths: 'Strong ERP and enterprise software expertise, 500+ certified consultants, partnerships with SAP/Oracle/Microsoft, proven government implementations',
        weaknesses: 'Expensive consulting rates ($200+/hr), scope creep issues on 30% of past projects, limited hardware/infrastructure capability',
        typicalBidStyle: 'Solution-heavy proposals with strong architecture diagrams and demos. Premium pricing justified by brand partnerships. Wins on technical evaluation.',
        notes: 'Recently won Maharashtra state police digitization project. Has dedicated government practice with 150 consultants.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'NexGen Facilities',
        industries: ['retail', 'hospitality', 'commercial-real-estate', 'healthcare'],
        strengths: 'Largest FM workforce in India (25,000+ staff), proprietary CAFM platform, strong retail chain experience (managing 2000+ stores), energy management expertise',
        weaknesses: 'Thin margins leading to service quality issues, high attrition in housekeeping staff (60% annual), limited technology innovation beyond CAFM',
        typicalBidStyle: 'Volume-driven pricing with aggressive per-sq-ft rates. Wins on scale and geographic coverage. Weak on innovation scores.',
        notes: 'Currently manages facilities for Future Group, Spencer\'s, and Shoppers Stop. IPO planned for 2027.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'SolarMax Energy',
        industries: ['renewable-energy', 'green-energy', 'power', 'infrastructure'],
        strengths: '2 GW+ solar capacity commissioned, in-house module manufacturing (BIS certified), strong O&M track record with 24%+ CUF, partnerships with Tier-1 module suppliers',
        weaknesses: 'Overleveraged balance sheet (debt-equity 2.5:1), limited BESS experience, concentrated in Rajasthan/Gujarat only',
        typicalBidStyle: 'Aggressive tariff bids leveraging in-house manufacturing cost advantage. Technical proposals heavy on track record. Wins on lowest LCOE.',
        notes: 'Commissioned India\'s largest single-location solar plant (600 MW) in Barmer. Under CDR restructuring for 2 projects.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'PortConnect International',
        industries: ['port', 'logistics', 'shipping', 'supply-chain'],
        strengths: 'Global port operator managing 12 terminals worldwide, proprietary TOS (PortOS), deep draft vessel handling expertise, strong safety record (ISPS compliant)',
        weaknesses: 'Premium pricing (20% above local operators), slow decision-making due to global HQ approvals, limited inland logistics capability',
        typicalBidStyle: 'Premium proposals with strong global benchmarking data. High license fees compensated by operational efficiency gains. Wins on throughput improvement plans.',
        notes: 'Operates terminals in Dubai, Singapore, Rotterdam, and Mumbai (JNPT). Expanding into East Coast India ports.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'CampusTech Networks',
        industries: ['education', 'research', 'government', 'enterprise-networking'],
        strengths: 'Specialized in academic networks, deployed infrastructure at 50+ universities, strong Cisco/Juniper partnerships, dedicated education practice team',
        weaknesses: 'Small company (200 employees), limited financial capacity for large projects, no data center build expertise',
        typicalBidStyle: 'Education-focused proposals with heavy emphasis on research network requirements and academic use cases. Competitive pricing for education sector.',
        notes: 'Deployed networks at IIT Delhi, IIT Bombay, and IISc. Strong relationships with MHRD/UGC procurement teams.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'Wipro Infrastructure Engineering',
        industries: ['government', 'smart-city', 'healthcare', 'education', 'enterprise-IT'],
        strengths: 'Massive scale (100,000+ employees), end-to-end IT services capability, strong government empanelment (MeitY, NIC), financial stability (Fortune 500)',
        weaknesses: 'Bureaucratic proposal process, key personnel frequently rotated across projects, premium pricing for government projects, cookie-cutter solutions',
        typicalBidStyle: 'Comprehensive proposals leveraging brand and scale. Standard frameworks customized per RFP. Wins on credentials and financial stability.',
        notes: 'Has dedicated Smart City practice. Won 8 ICCC projects under Smart Cities Mission. Preferred vendor for NIC.',
      },
    }),
    // ─── ESP / POLLUTION CONTROL COMPETITORS ───
    prisma.competitor.create({
      data: {
        name: 'Thermax Limited',
        industries: ['pollution-control', 'steel', 'power', 'cement', 'chemical', 'refinery'],
        strengths: 'India\'s largest pollution control equipment manufacturer, 50+ years experience, in-house R&D center with 200+ engineers, 3 manufacturing plants (Pune, Savli, Jhagadia), 2000+ ESP installations globally, strong steel sector presence with JSW/Tata/SAIL references',
        weaknesses: 'Premium pricing (10-15% above Chinese imports), longer delivery times (20-22 months vs 16 for competitors), conservative designs with higher material consumption',
        typicalBidStyle: 'Technically superior proposals with extensive CFD simulations and reference data. Premium pricing justified by performance guarantees and lifecycle cost. Wins on technical evaluation in 70% of bids.',
        notes: 'Holds 35% market share in Indian ESP market. Recently acquired European ESP technology from Babcock & Wilcox. Preferred vendor for Tata Steel and SAIL.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'BHEL (Bharat Heavy Electricals Limited)',
        industries: ['pollution-control', 'power', 'steel', 'cement', 'heavy-engineering'],
        strengths: 'Government-owned with massive manufacturing capacity (14 plants), lowest cost structure due to scale, strong presence in power sector ESPs (500+ installations), government project preference, huge spare parts inventory',
        weaknesses: 'Bureaucratic decision-making, longer project timelines (25-30% slower than private players), limited innovation in SMPS/digital controls, quality consistency issues across manufacturing plants',
        typicalBidStyle: 'Lowest price bids leveraging government subsidies and scale. Wins on L1 (lowest qualified bidder) in government projects. Weak on innovation and modern control systems.',
        notes: 'Dominant in NTPC and state power utility ESPs. Trying to expand into steel sector. Recently lost 3 steel ESP orders to Thermax and FLSmidth.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'FLSmidth (India)',
        industries: ['pollution-control', 'cement', 'mining', 'steel', 'minerals-processing'],
        strengths: 'Global leader in cement and minerals ESP, proprietary SMPS technology (EAC-2000), 100+ years heritage, strong R&D (Denmark HQ), best-in-class gas distribution design, low energy consumption ESPs',
        weaknesses: 'Very expensive (20-30% premium), limited local manufacturing in India (assembly only in Chennai), long lead times for imported components, small India service team (80 people)',
        typicalBidStyle: 'Technology-led proposals with global benchmarking data. Highest pricing but strongest performance guarantees. Wins when technical score is heavily weighted (>50%).',
        notes: 'Recently won Tata Steel Kalinganagar ESP order. Expanding India operations. Partnered with local fabricator for cost reduction.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'Hamon (India) Pvt Ltd',
        industries: ['pollution-control', 'steel', 'power', 'refinery', 'petrochemical'],
        strengths: 'Belgian technology with Indian manufacturing (Vadodara plant), excellent sinter plant ESP track record (30+ installations globally), patented rigid discharge electrode design, competitive pricing, good after-sales support network',
        weaknesses: 'Smaller company in India (150 employees), limited civil construction capability (subcontracts civil), parent company financial instability (restructuring), single manufacturing facility',
        typicalBidStyle: 'Balanced proposals with strong sinter plant references. Mid-range pricing with good performance guarantees. Wins on steel-specific experience and electrode technology.',
        notes: 'Installed ESPs at JSW Dolvi, Tata Steel Jamshedpur, and RINL Vizag sinter plants. Strong technical team with European-trained engineers.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'Scheuch India',
        industries: ['pollution-control', 'steel', 'cement', 'waste-incineration', 'biomass'],
        strengths: 'Austrian technology leader, proprietary EMC (Electro-dynamic Mist Collector) for wet applications, advanced digital ESP controls with AI optimization, strong European steel references (ArcelorMittal, ThyssenKrupp), energy-efficient designs',
        weaknesses: 'New entrant in India (established 2021), no local manufacturing (imports from Austria/China), very small India team (25 people), no Indian steel plant references yet, premium pricing',
        typicalBidStyle: 'Innovation-focused proposals highlighting energy savings and digital controls. Highest pricing but lowest operating cost. Targets projects where energy consumption is heavily weighted.',
        notes: 'Trying to break into Indian steel market. Offered aggressive pricing on first 2 Indian bids. Partnership with Elecon Engineering for local fabrication.',
      },
    }),
    prisma.competitor.create({
      data: {
        name: 'Unicon International',
        industries: ['pollution-control', 'steel', 'power', 'cement', 'smelter', 'fertilizer'],
        strengths: 'Established Indian ESP specialist with 25+ years experience, 400+ ESP installations across India, strong steel sector presence (JSW, SAIL, JSPL, Essar), in-house manufacturing in Ahmedabad (40,000 sqm), competitive pricing with reliable quality, excellent after-sales network across India',
        weaknesses: 'Limited international presence (India-focused), smaller R&D budget compared to global players, dependent on imported TR sets for high-end projects, moderate digital/automation capability',
        typicalBidStyle: 'Value-for-money proposals with strong Indian reference data. Competitive pricing (5-10% below Thermax). Wins on combination of price and proven steel sector experience.',
        notes: 'Recently completed Head End ESP for sinter plant at a leading Indian steel conglomerate handling 13.5 lakh m³/hr with <30 mg/Nm³ guarantee. Strong relationship with JSW and JSPL procurement teams.',
      },
    }),
  ]);

  console.log(`Created ${competitors.length} competitors`);

  // ─── HISTORICAL BIDS ───
  const historicalBids = await Promise.all([
    // Airport bids - Our company
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Mumbai International Airport - Advertising Concession 2024',
        clientName: 'Mumbai International Airport Ltd (MIAL)',
        industry: 'airport',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 5000000,
        profitSharePct: 12.5,
        outcome: 'won',
        scoreReceived: 87.5,
        otherTerms: {
          contract_value_total: 32500000,
          annual_revenue_generated: 7800000,
          ad_occupancy_rate_pct: 92.3,
          digital_screens_deployed: 185,
          static_panels_managed: 120,
          advertiser_brands_onboarded: 78,
          avg_advertiser_roi_pct: 340,
          passenger_impressions_daily: 185000,
          display_uptime_pct: 99.6,
          revenue_growth_yoy_pct: 18.5,
          team_size_deployed: 32,
          implementation_days: 90,
          client_satisfaction_score: 4.6,
          energy_savings_pct: 22,
          programmatic_ad_revenue_pct: 35,
        },
        lessonsLearned: 'Strong experience section and competitive revenue model sealed the deal. Digital innovation proposal with real-time analytics dashboard was a key differentiator. Client appreciated the phased rollout plan.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Delhi Airport T3 - Media Rights 2023',
        clientName: 'Delhi International Airport Ltd (DIAL)',
        industry: 'airport',
        year: 2023,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 8000000,
        profitSharePct: 10.0,
        outcome: 'lost',
        winningBidSummary: 'AdVision Global won with $9.5M guarantee and 11% share. Their experience section scored 23/25 vs our 18/25. They highlighted 12 airport contracts vs our 6.',
        scoreReceived: 72.0,
        otherTerms: {
          our_bid_total_value: 44000000,
          winning_bid_total_value: 52250000,
          gap_to_winner_pct: 15.8,
          experience_score: 18,
          experience_max: 25,
          technical_score: 17,
          technical_max: 20,
          financial_score: 28,
          financial_max: 40,
          airport_contracts_cited: 6,
          winner_airport_contracts: 12,
        },
        lessonsLearned: 'Need to strengthen experience section with more specific case studies and measurable ROI data. Revenue model was close but guarantee amount was $1.5M below winner. Must improve airport-specific references.',
        competitor: { connect: { id: competitors[0].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Chennai Airport - Digital Signage Upgrade 2025',
        clientName: 'Airports Authority of India - Chennai',
        industry: 'airport',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 3200000,
        profitSharePct: 14.0,
        outcome: 'won',
        scoreReceived: 91.0,
        otherTerms: {
          contract_value_total: 19200000,
          digital_screens_installed: 220,
          led_video_walls: 8,
          interactive_kiosks: 15,
          avg_dwell_time_increase_pct: 28,
          ad_recall_rate_pct: 67,
          passenger_engagement_rate_pct: 12.4,
          annual_ad_revenue: 4600000,
          advertiser_retention_rate_pct: 94,
          content_updates_per_day: 450,
          ai_content_scheduling_accuracy_pct: 96.2,
          display_uptime_pct: 99.7,
          energy_cost_reduction_pct: 35,
          implementation_completed_weeks: 14,
          team_size_deployed: 18,
        },
        lessonsLearned: 'Digital-first approach scored highest in technical evaluation. Proposed AI-driven content scheduling based on flight data was the winning differentiator. Higher profit share compensated for moderate guarantee.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Kolkata Airport - Advertising Rights 2024',
        clientName: 'Airports Authority of India - Kolkata',
        industry: 'airport',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 2800000,
        profitSharePct: 11.0,
        outcome: 'lost',
        winningBidSummary: 'SkyMedia Partners won with luxury-focused proposal at $3.5M MAG and 15% share. They brought exclusive luxury brand commitments.',
        scoreReceived: 68.0,
        lessonsLearned: 'For airports with high international traffic, luxury brand partnerships matter significantly. Need to develop premium advertiser relationships. Lost mainly on financial offer and brand portfolio.',
        competitor: { connect: { id: competitors[3].id } },
      },
    }),

    // Airport bids - Competitors
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Bangalore Airport - Digital Advertising 2024',
        clientName: 'Bangalore International Airport Ltd (BIAL)',
        industry: 'airport',
        year: 2024,
        bidderName: 'MediaReach Corp',
        isOurBid: false,
        flatGuarantee: 3500000,
        profitSharePct: 15.0,
        outcome: 'won',
        scoreReceived: 91.0,
        lessonsLearned: 'MediaReach won with innovative digital-first proposal featuring AR experiences. Higher profit share compensated for lower guarantee. Their tech platform demo during presentation was decisive.',
        competitor: { connect: { id: competitors[1].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Hyderabad Airport - Media Concession 2023',
        clientName: 'GMR Hyderabad International Airport',
        industry: 'airport',
        year: 2023,
        bidderName: 'AdVision Global',
        isOurBid: false,
        flatGuarantee: 6500000,
        profitSharePct: 9.0,
        outcome: 'won',
        scoreReceived: 85.0,
        lessonsLearned: 'AdVision leveraged their existing relationship with GMR group. High guarantee amount was decisive. They offered dedicated on-site team of 25 people.',
        competitor: { connect: { id: competitors[0].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'City Metro Station Advertising - 2023',
        clientName: 'Metro Rail Corporation',
        industry: 'transit',
        year: 2023,
        bidderName: 'AdVision Global',
        isOurBid: false,
        flatGuarantee: 2000000,
        profitSharePct: 8.0,
        outcome: 'won',
        lessonsLearned: 'Transit advertising requires different approach than airport. Foot traffic patterns and commuter demographics are key pricing factors.',
        competitor: { connect: { id: competitors[0].id } },
      },
    }),

    // Construction bids - Our company
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'National Highway Construction - Phase IV',
        clientName: 'National Highways Authority of India (NHAI)',
        industry: 'construction',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 25000000,
        profitSharePct: 5.0,
        outcome: 'won',
        scoreReceived: 82.0,
        otherTerms: {
          project_value_inr_crores: 420,
          highway_length_km: 86.5,
          lanes_constructed: 4,
          completion_ahead_of_schedule_days: 45,
          safety_record_ltifr: 0.12,
          zero_fatality_incidents: true,
          workforce_deployed: 1800,
          heavy_equipment_units: 120,
          concrete_poured_cubic_meters: 385000,
          quality_audit_score_pct: 97.2,
          cost_underrun_pct: 3.8,
          milestones_met_on_time_pct: 94,
          environmental_compliance_score: 98,
          local_employment_pct: 72,
        },
        lessonsLearned: 'Government contracts value experience and safety record highly. Cost competitiveness matters but is not the only factor. Detailed project timeline with milestones impressed the evaluation committee.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Smart City Infrastructure - Pune Phase II',
        clientName: 'Pune Smart City Development Corporation',
        industry: 'construction',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 18000000,
        profitSharePct: 6.5,
        outcome: 'won',
        scoreReceived: 88.0,
        otherTerms: {
          project_value_inr_crores: 310,
          iot_sensors_deployed: 1850,
          smart_streetlights_installed: 1200,
          cctv_cameras_installed: 350,
          fiber_optic_laid_km: 125,
          citizen_app_downloads: 280000,
          citizen_app_active_users_monthly: 85000,
          grievance_resolution_time_hours: 18,
          energy_savings_achieved_pct: 32,
          traffic_congestion_reduction_pct: 18,
          water_leakage_detection_improvement_pct: 45,
          data_dashboard_uptime_pct: 99.8,
          implementation_months: 16,
          team_size_deployed: 85,
        },
        lessonsLearned: 'Smart city projects require strong technology integration plan. IoT sensor deployment strategy and data dashboard proposal were key differentiators. Sustainability section scored full marks.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Mumbai Coastal Road - Segment 3 Construction',
        clientName: 'Brihanmumbai Municipal Corporation (BMC)',
        industry: 'construction',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 45000000,
        profitSharePct: 3.5,
        outcome: 'lost',
        winningBidSummary: 'BuildMax won with lowest bid at $38M guarantee. Their aggressive pricing undercut all competitors by 15%.',
        scoreReceived: 75.0,
        lessonsLearned: 'BMC heavily weighted financial offer (50% of score). Need to be more aggressive on pricing for municipal projects. Lost despite higher technical scores.',
        competitor: { connect: { id: competitors[2].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Green Office Complex - Gurugram',
        clientName: 'DLF Limited',
        industry: 'construction',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 12000000,
        profitSharePct: 8.0,
        outcome: 'lost',
        winningBidSummary: 'GreenBuild Sustainable won with LEED Platinum commitment and 20% lower carbon footprint proposal at $13.5M guarantee.',
        scoreReceived: 71.0,
        lessonsLearned: 'ESG-focused clients increasingly prioritize sustainability over cost. Need to develop green building certifications and sustainable material partnerships.',
        competitor: { connect: { id: competitors[6].id } },
      },
    }),

    // Construction bids - Competitors
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Metro Rail Extension - Phase 2',
        clientName: 'Delhi Metro Rail Corporation (DMRC)',
        industry: 'construction',
        year: 2024,
        bidderName: 'InfraCore Builders',
        isOurBid: false,
        flatGuarantee: 55000000,
        profitSharePct: 4.0,
        outcome: 'won',
        scoreReceived: 86.0,
        lessonsLearned: 'InfraCore won on government experience (25 years) and safety record (zero fatalities). Their bonding capacity allowed them to offer performance guarantees others could not match.',
        competitor: { connect: { id: competitors[5].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Solar Farm Installation - Rajasthan 500MW',
        clientName: 'Rajasthan Renewable Energy Corporation',
        industry: 'construction',
        year: 2025,
        bidderName: 'GreenBuild Sustainable',
        isOurBid: false,
        flatGuarantee: 30000000,
        profitSharePct: 7.0,
        outcome: 'won',
        scoreReceived: 93.0,
        lessonsLearned: 'Renewable energy projects heavily favor companies with green credentials. GreenBuild scored 5/5 on sustainability and 9/10 on technical approach.',
        competitor: { connect: { id: competitors[6].id } },
      },
    }),

    // Logistics bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Port Logistics Management - Mundra Port',
        clientName: 'Adani Ports and SEZ Limited',
        industry: 'logistics',
        year: 2024,
        bidderName: 'Vortex Logistics Solutions',
        isOurBid: false,
        flatGuarantee: 15000000,
        profitSharePct: 6.0,
        outcome: 'won',
        scoreReceived: 89.0,
        lessonsLearned: 'Vortex won on operational efficiency metrics and AI-powered optimization. Their 99.7% on-time delivery record was unmatched.',
        competitor: { connect: { id: competitors[4].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'E-commerce Warehouse Network - Pan India',
        clientName: 'Flipkart Internet Pvt Ltd',
        industry: 'logistics',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 20000000,
        profitSharePct: 7.5,
        outcome: 'won',
        scoreReceived: 84.0,
        otherTerms: {
          warehouses_managed: 18,
          total_area_sqft: 2200000,
          orders_processed_daily: 320000,
          peak_orders_daily: 1200000,
          order_accuracy_rate_pct: 99.4,
          on_time_dispatch_rate_pct: 97.8,
          avg_pick_pack_time_minutes: 4.2,
          automated_sorting_throughput_per_hour: 15000,
          inventory_accuracy_pct: 99.7,
          return_processing_time_hours: 6,
          workforce_deployed: 4500,
          cost_per_order_usd: 0.42,
          damage_rate_pct: 0.08,
          same_day_delivery_cities: 12,
          technology_investment_usd: 3500000,
        },
        lessonsLearned: 'E-commerce logistics requires 24/7 operations capability. Our automated sorting system proposal and same-day delivery commitment were decisive factors.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Cold Chain Logistics - Pharmaceutical Distribution',
        clientName: 'Sun Pharmaceutical Industries',
        industry: 'logistics',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 8000000,
        profitSharePct: 9.0,
        outcome: 'lost',
        winningBidSummary: 'Vortex won with specialized cold chain infrastructure and GDP compliance certification. Their temperature monitoring IoT system was a major differentiator.',
        scoreReceived: 69.0,
        lessonsLearned: 'Pharmaceutical logistics requires specialized certifications (GDP, WHO guidelines). Need to invest in cold chain capabilities and compliance certifications.',
        competitor: { connect: { id: competitors[4].id } },
      },
    }),

    // Healthcare / Government bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Hospital Digital Signage - AIIMS Network',
        clientName: 'All India Institute of Medical Sciences',
        industry: 'healthcare',
        year: 2025,
        bidderName: 'MediaReach Corp',
        isOurBid: false,
        flatGuarantee: 1500000,
        profitSharePct: 12.0,
        outcome: 'won',
        scoreReceived: 88.0,
        lessonsLearned: 'Healthcare advertising requires sensitivity and compliance with medical advertising guidelines. MediaReach content filtering AI was the differentiator.',
        competitor: { connect: { id: competitors[1].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Government Office Complex - New Delhi',
        clientName: 'Central Public Works Department (CPWD)',
        industry: 'government',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 35000000,
        profitSharePct: 4.0,
        outcome: 'won',
        scoreReceived: 80.0,
        otherTerms: {
          project_value_inr_crores: 580,
          building_area_sqft: 450000,
          floors_constructed: 12,
          completion_time_months: 28,
          green_building_rating: 'GRIHA 4-Star',
          energy_efficiency_improvement_pct: 28,
          water_recycling_capacity_liters_daily: 50000,
          solar_panel_capacity_kw: 250,
          parking_spaces_created: 800,
          safety_incidents: 0,
          workforce_peak: 2200,
          compliance_audits_passed: 14,
          cost_variance_pct: 2.1,
          client_satisfaction_score: 4.3,
        },
        lessonsLearned: 'Government projects require meticulous documentation and compliance. L1 bidding (lowest qualified bid) is common. Relationship with CPWD officials helped in clarification rounds.',
      },
    }),

    // ─── NEW HISTORICAL BIDS ───

    // Healthcare bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Hospital Digital Transformation - Fortis Network',
        clientName: 'Fortis Healthcare Limited',
        industry: 'healthcare',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 8500000,
        profitSharePct: 10.0,
        outcome: 'won',
        scoreReceived: 85.0,
        otherTerms: {
          hospitals_deployed: 12,
          digital_displays_installed: 650,
          patient_info_kiosks: 85,
          telemedicine_rooms_setup: 36,
          avg_patient_wait_time_reduction_pct: 34,
          patient_satisfaction_improvement_pct: 22,
          opd_queue_management_efficiency_pct: 41,
          emr_integration_success_rate_pct: 99.2,
          daily_patient_interactions_digital: 45000,
          system_uptime_pct: 99.85,
          avg_response_time_ms: 120,
          multilingual_languages_supported: 5,
          staff_training_hours_completed: 8500,
          hipaa_compliance_audit_score_pct: 98,
          annual_ad_revenue_from_health_brands: 1200000,
          go_live_hospitals_in_phase1: 6,
          implementation_phase1_weeks: 20,
        },
        lessonsLearned: 'Healthcare IT projects require deep understanding of clinical workflows. Our EMR integration demo during the presentation was the turning point. HIPAA compliance documentation was critical.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Multi-Hospital Patient Information System - Max Healthcare',
        clientName: 'Max Healthcare Institute Limited',
        industry: 'healthcare',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 6000000,
        profitSharePct: 8.0,
        outcome: 'lost',
        winningBidSummary: 'TechSphere Solutions won with SAP Health platform and 3 existing hospital references. Their dedicated healthcare practice team of 50 consultants was decisive.',
        scoreReceived: 72.0,
        lessonsLearned: 'Need specialized healthcare IT certifications and dedicated practice team. Generic IT proposals do not win in healthcare. Must invest in HL7/FHIR integration capabilities.',
        competitor: { connect: { id: competitors[7].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Telemedicine Platform - Government of Kerala',
        clientName: 'Kerala Health Services Department',
        industry: 'healthcare',
        year: 2025,
        bidderName: 'MediaReach Corp',
        isOurBid: false,
        flatGuarantee: 4000000,
        profitSharePct: 11.0,
        outcome: 'won',
        scoreReceived: 90.0,
        lessonsLearned: 'MediaReach leveraged their AIIMS success and health-tech platform. Multilingual support (Malayalam, Tamil, Hindi) was a key differentiator for Kerala government.',
        competitor: { connect: { id: competitors[1].id } },
      },
    }),

    // Smart City / Government IT bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Indore Smart City ICCC Implementation',
        clientName: 'Indore Smart City Development Ltd',
        industry: 'smart-city',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 42000000,
        profitSharePct: 5.5,
        outcome: 'won',
        scoreReceived: 83.0,
        otherTerms: {
          iccc_facility_sqft: 8500,
          video_wall_displays: 42,
          iot_sensors_deployed: 2200,
          smart_streetlights: 1500,
          traffic_cameras_ai: 380,
          air_quality_stations: 45,
          smart_parking_sensors: 120,
          emergency_response_time_reduction_pct: 42,
          traffic_violation_detection_accuracy_pct: 94.5,
          citizen_app_users: 195000,
          grievances_resolved_monthly: 12000,
          avg_resolution_time_hours: 22,
          data_points_processed_daily_millions: 8.5,
          system_uptime_pct: 99.9,
          energy_savings_city_wide_pct: 18,
          crime_reduction_in_monitored_areas_pct: 23,
          api_integrations_count: 28,
          implementation_months: 18,
          team_deployed: 65,
        },
        lessonsLearned: 'Smart city ICCC projects require strong IoT platform and integration capability. Our open-API approach for third-party integrations impressed the evaluation committee. Citizen app engagement metrics from Pune project were a strong reference.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Surat Smart City - ICCC Phase 2',
        clientName: 'Surat Smart City Development Ltd',
        industry: 'smart-city',
        year: 2025,
        bidderName: 'Wipro Infrastructure Engineering',
        isOurBid: false,
        flatGuarantee: 48000000,
        profitSharePct: 4.5,
        outcome: 'won',
        scoreReceived: 86.0,
        lessonsLearned: 'Wipro won on scale and existing Smart City Mission credentials (8 ICCC projects). Their MeitY empanelment and NIC integration experience was decisive. We lost on government experience criterion.',
        competitor: { connect: { id: competitors[12].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Rajasthan State ERP - Phase 1',
        clientName: 'Department of IT, Government of Rajasthan',
        industry: 'government',
        year: 2024,
        bidderName: 'TechSphere Solutions',
        isOurBid: false,
        flatGuarantee: 65000000,
        profitSharePct: 3.0,
        outcome: 'won',
        scoreReceived: 88.0,
        lessonsLearned: 'Government ERP projects require CMMI Level 5 and deep government domain expertise. TechSphere won on SAP platform maturity and 500+ consultant bench strength.',
        competitor: { connect: { id: competitors[7].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Bihar State Data Center & Cloud Infrastructure',
        clientName: 'Bihar State Electronics Development Corp',
        industry: 'government',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 28000000,
        profitSharePct: 5.0,
        outcome: 'lost',
        winningBidSummary: 'Wipro won with MeghRaj cloud expertise and NIC integration track record. Their existing empanelment with MeitY streamlined the procurement process.',
        scoreReceived: 74.0,
        lessonsLearned: 'Government cloud projects heavily favor MeitY-empaneled vendors. Need to invest in government cloud certifications and NIC integration experience.',
        competitor: { connect: { id: competitors[12].id } },
      },
    }),

    // Renewable Energy bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Karnataka 400 MW Solar Park - EPC',
        clientName: 'Karnataka Renewable Energy Development Ltd',
        industry: 'renewable-energy',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 280000000,
        profitSharePct: 4.0,
        outcome: 'won',
        scoreReceived: 82.0,
        otherTerms: {
          capacity_mw: 400,
          modules_installed: 800000,
          land_area_acres: 1800,
          epc_cost_per_mw_inr_lakhs: 350,
          achieved_cuf_pct: 23.8,
          annual_generation_gwh: 835,
          co2_offset_tonnes_annual: 680000,
          bess_capacity_mwh: 100,
          transmission_line_km: 28,
          substations_built: 3,
          construction_completion_months: 20,
          peak_workforce: 3200,
          safety_incidents: 0,
          module_degradation_yr1_pct: 0.45,
          inverter_efficiency_pct: 98.6,
          plant_availability_pct: 99.3,
          lcoe_inr_per_kwh: 2.58,
          local_content_pct: 68,
        },
        lessonsLearned: 'Solar EPC bids are heavily cost-driven. Our partnership with Tier-1 module supplier and local EPC team reduced costs by 8%. Detailed BESS integration plan was a differentiator since most competitors had limited battery storage experience.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Gujarat 600 MW Wind-Solar Hybrid Project',
        clientName: 'Gujarat Urja Vikas Nigam Limited (GUVNL)',
        industry: 'renewable-energy',
        year: 2024,
        bidderName: 'SolarMax Energy',
        isOurBid: false,
        flatGuarantee: 350000000,
        profitSharePct: 3.5,
        outcome: 'won',
        scoreReceived: 89.0,
        lessonsLearned: 'SolarMax won with lowest LCOE bid (INR 2.45/kWh) leveraging in-house module manufacturing. Their 24.2% CUF track record was unmatched. We need to develop manufacturing partnerships to compete on cost.',
        competitor: { connect: { id: competitors[9].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Ladakh 50 MW Solar with BESS - SECI',
        clientName: 'Solar Energy Corporation of India (SECI)',
        industry: 'renewable-energy',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 55000000,
        profitSharePct: 5.5,
        outcome: 'lost',
        winningBidSummary: 'GreenBuild Sustainable won with strong BESS expertise and high-altitude solar installation experience from Nepal projects. Their cold-weather module performance data was decisive.',
        scoreReceived: 70.0,
        lessonsLearned: 'Extreme climate solar projects require specialized module certifications (IEC 62446 for cold climate). BESS sizing for high-altitude conditions needs dedicated engineering capability.',
        competitor: { connect: { id: competitors[6].id } },
      },
    }),

    // Port & Logistics bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Chennai Port Container Terminal Modernization',
        clientName: 'Chennai Port Authority',
        industry: 'port',
        year: 2024,
        bidderName: 'PortConnect International',
        isOurBid: false,
        flatGuarantee: 22000000,
        profitSharePct: 7.0,
        outcome: 'won',
        scoreReceived: 91.0,
        lessonsLearned: 'PortConnect won on global benchmarking data showing 40% throughput improvement at similar ports. Their proprietary TOS (PortOS) and automated STS crane experience was unmatched.',
        competitor: { connect: { id: competitors[10].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Kandla Port Bulk Cargo Logistics',
        clientName: 'Deendayal Port Authority',
        industry: 'port',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 18000000,
        profitSharePct: 6.5,
        outcome: 'won',
        scoreReceived: 81.0,
        otherTerms: {
          cargo_handled_mmt_annual: 12.5,
          berths_managed: 4,
          vessel_turnaround_time_days: 2.8,
          truck_movements_daily: 380,
          warehouse_area_sqm: 85000,
          crane_operations_daily: 120,
          throughput_improvement_pct: 28,
          dust_suppression_reduction_pct: 75,
          safety_record_ltifr: 0.08,
          workforce_deployed: 650,
          local_hiring_pct: 82,
          equipment_availability_pct: 96.5,
          environmental_compliance_score_pct: 97,
          cargo_damage_rate_pct: 0.02,
          avg_loading_time_reduction_hours: 4.2,
        },
        lessonsLearned: 'Bulk cargo logistics at ports requires different skill set than container handling. Our dust suppression system and environmental management plan scored highest. Local workforce deployment plan was appreciated by port authority.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Reliance Jio Warehouse Network Expansion',
        clientName: 'Reliance Jio Infocomm Limited',
        industry: 'logistics',
        year: 2025,
        bidderName: 'Vortex Logistics Solutions',
        isOurBid: false,
        flatGuarantee: 25000000,
        profitSharePct: 8.0,
        outcome: 'won',
        scoreReceived: 87.0,
        lessonsLearned: 'Vortex won on existing Reliance relationship and telecom equipment handling expertise. Their 50-city warehouse network was pre-positioned for the requirement.',
        competitor: { connect: { id: competitors[4].id } },
      },
    }),

    // Retail FM bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Shoppers Stop - Integrated Facility Management',
        clientName: 'Shoppers Stop Limited',
        industry: 'retail',
        year: 2024,
        bidderName: 'NexGen Facilities',
        isOurBid: false,
        flatGuarantee: 9000000,
        profitSharePct: 5.0,
        outcome: 'won',
        scoreReceived: 83.0,
        lessonsLearned: 'NexGen won on volume pricing and existing retail FM experience (2000+ stores managed). Their CAFM platform with real-time SLA dashboards impressed the evaluation committee.',
        competitor: { connect: { id: competitors[8].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'DMart - Facility Management Services',
        clientName: 'Avenue Supermarts Limited',
        industry: 'retail',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 7500000,
        profitSharePct: 6.0,
        outcome: 'won',
        scoreReceived: 79.0,
        otherTerms: {
          stores_managed: 180,
          total_area_managed_sqft: 1800000,
          cost_per_sqft_monthly_inr: 4.2,
          energy_savings_achieved_pct: 14.5,
          energy_cost_saved_annual_inr_lakhs: 320,
          hvac_uptime_pct: 99.2,
          avg_maintenance_response_time_minutes: 25,
          preventive_maintenance_compliance_pct: 96,
          pest_control_incidents_per_store_monthly: 0.3,
          housekeeping_audit_score_pct: 92,
          staff_deployed: 720,
          staff_attrition_rate_pct: 28,
          fire_safety_compliance_pct: 100,
          customer_complaint_resolution_hours: 4,
          iot_sensors_deployed_for_hvac: 540,
          cafm_work_orders_monthly: 4200,
        },
        lessonsLearned: 'DMart values cost efficiency above all. Our lean staffing model with technology-enabled monitoring won over more expensive proposals. Energy savings guarantee of 12% was a key differentiator.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Lifestyle International - Store FM Pan India',
        clientName: 'Lifestyle International Pvt Ltd',
        industry: 'retail',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 11000000,
        profitSharePct: 7.0,
        outcome: 'lost',
        winningBidSummary: 'NexGen Facilities won with lowest per-sq-ft rate and 300-store management track record. Their existing Lifestyle pilot in Bangalore gave them insider advantage.',
        scoreReceived: 73.0,
        lessonsLearned: 'Retail FM is highly competitive on price. Need to invest in CAFM platform to match NexGen capabilities. Pilot project relationships matter for full portfolio wins.',
        competitor: { connect: { id: competitors[8].id } },
      },
    }),

    // Education / Campus Network bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'IIT Bombay Campus Network Upgrade',
        clientName: 'Indian Institute of Technology Bombay',
        industry: 'education',
        year: 2024,
        bidderName: 'CampusTech Networks',
        isOurBid: false,
        flatGuarantee: 10000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 92.0,
        lessonsLearned: 'CampusTech won on deep education sector expertise and existing IIT relationships. Their research network design supporting 400 Gbps backbone with HPC integration was technically superior.',
        competitor: { connect: { id: competitors[11].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'BITS Pilani - Digital Campus Infrastructure',
        clientName: 'Birla Institute of Technology and Science',
        industry: 'education',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 8000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 84.0,
        otherTerms: {
          campus_area_acres: 300,
          buildings_networked: 85,
          wifi_access_points_deployed: 1800,
          backbone_bandwidth_gbps: 200,
          concurrent_users_supported: 12000,
          lms_courses_migrated: 450,
          smart_classrooms_setup: 65,
          lecture_capture_rooms: 40,
          avg_network_latency_ms: 2.1,
          wifi_coverage_pct: 98.5,
          network_uptime_pct: 99.95,
          data_center_racks: 45,
          cybersecurity_incidents_blocked_monthly: 15000,
          student_satisfaction_survey_pct: 88,
          bandwidth_per_user_mbps: 50,
          implementation_months: 14,
          training_sessions_conducted: 120,
          faculty_trained: 380,
        },
        lessonsLearned: 'Won on integrated approach combining network infrastructure with digital learning platform. LMS integration with existing BITS online programs was the differentiator. Wi-Fi 7 POC on campus convinced the evaluation committee.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Delhi University - Campus Wi-Fi & Network',
        clientName: 'University of Delhi',
        industry: 'education',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 12000000,
        profitSharePct: 0,
        outcome: 'lost',
        winningBidSummary: 'Wipro won on government procurement empanelment and NKN (National Knowledge Network) integration experience. Their GeM listing simplified procurement for the university.',
        scoreReceived: 71.0,
        lessonsLearned: 'Government-funded university projects follow government procurement norms. GeM listing and NKN integration capability are prerequisites. Need to get empaneled with MHRD/UGC.',
        competitor: { connect: { id: competitors[12].id } },
      },
    }),

    // ─── ESP / POLLUTION CONTROL BIDS ───

    // Our Company ESP bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Tata Steel Kalinganagar - Sinter Plant ESP',
        clientName: 'Tata Steel Limited - Kalinganagar',
        industry: 'pollution-control',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 28000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 84.0,
        otherTerms: {
          esp_capacity_m3_hr: 1150000,
          inlet_dust_load_g_nm3: 2.5,
          guaranteed_outlet_mg_nm3: 25,
          achieved_outlet_mg_nm3: 18.2,
          collection_efficiency_pct: 99.2,
          number_of_fields: 4,
          collecting_area_m2: 28500,
          tr_sets_installed: 8,
          power_consumption_kw: 1850,
          specific_power_wh_per_1000m3: 1.61,
          pressure_drop_pa: 180,
          mechanical_completion_months: 16,
          commissioning_weeks: 8,
          pgt_duration_hours: 72,
          total_steel_used_tonnes: 2800,
          workforce_peak: 450,
          safety_incidents: 0,
          man_hours_worked: 1200000,
          cems_integrated: true,
          dcs_integration: 'Siemens PCS7',
          client_satisfaction_score: 4.5,
        },
        lessonsLearned: 'Steel sector ESPs require robust rapping systems due to sticky sinter dust. Our rigid frame discharge electrode design outperformed wire-weight alternatives in PGT. CFD-optimized gas distribution achieved <15% velocity deviation. SMPS-based TR sets reduced power consumption by 22% vs conventional.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'JSPL Angul - BOF Gas Cleaning ESP',
        clientName: 'Jindal Steel & Power Limited - Angul',
        industry: 'pollution-control',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 35000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 81.0,
        otherTerms: {
          esp_capacity_m3_hr: 1800000,
          inlet_dust_load_g_nm3: 5.0,
          guaranteed_outlet_mg_nm3: 30,
          achieved_outlet_mg_nm3: 22.5,
          collection_efficiency_pct: 99.55,
          number_of_fields: 5,
          collecting_area_m2: 38000,
          tr_sets_installed: 10,
          power_consumption_kw: 2400,
          specific_power_wh_per_1000m3: 1.33,
          pressure_drop_pa: 220,
          mechanical_completion_months: 18,
          pgt_passed_first_attempt: true,
          ash_handling_capacity_tph: 45,
          total_project_cost_inr_crores: 295,
          civil_foundation_type: 'RCC pile foundation',
          insulation_thickness_mm: 100,
          cems_brand: 'Sick Maihak',
          dcs_integration: 'ABB 800xA',
        },
        lessonsLearned: 'BOF gas cleaning requires explosion-proof design with CO monitoring. 5-field ESP design gave additional safety margin for upset conditions. Pulse-energization mode on TR sets achieved 15% energy savings during low-load operation.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'SAIL Bhilai - Sinter Plant Waste Gas ESP Retrofit',
        clientName: 'Steel Authority of India Limited - Bhilai',
        industry: 'pollution-control',
        year: 2024,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 22000000,
        profitSharePct: 0,
        outcome: 'lost',
        winningBidSummary: 'BHEL won on L1 basis at INR 185 Crores vs our INR 218 Crores. SAIL being a government PSU preferred BHEL (also a PSU). Despite our higher technical score (52/60 vs 42/60), L1 procurement policy prevailed.',
        scoreReceived: 76.0,
        otherTerms: {
          our_technical_score: 52,
          winner_technical_score: 42,
          our_price_inr_crores: 218,
          winner_price_inr_crores: 185,
          price_gap_pct: 17.8,
          esp_capacity_m3_hr: 980000,
        },
        lessonsLearned: 'Government PSU steel plants follow L1 procurement policy. Price gap of 17.8% was too large despite superior technical scores. For SAIL/RINL/NMDC bids, need to reduce costs by at least 10% through value engineering. Consider partnering with BHEL as sub-supplier for PSU orders.',
        competitor: { connect: { id: competitors[14].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Essar Steel Hazira - Pellet Plant ESP',
        clientName: 'ArcelorMittal Nippon Steel India (Hazira)',
        industry: 'pollution-control',
        year: 2023,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 18000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 88.0,
        otherTerms: {
          esp_capacity_m3_hr: 850000,
          inlet_dust_load_g_nm3: 3.0,
          guaranteed_outlet_mg_nm3: 30,
          achieved_outlet_mg_nm3: 15.8,
          collection_efficiency_pct: 99.47,
          number_of_fields: 4,
          tr_set_type: 'SMPS high-frequency',
          collecting_area_m2: 22000,
          power_consumption_kw: 1200,
          energy_savings_vs_conventional_pct: 28,
          total_project_cost_inr_crores: 155,
          mechanical_completion_months: 14,
          commissioning_weeks: 6,
          training_hours_delivered: 48,
          warranty_period_months: 24,
          spare_parts_value_inr_lakhs: 85,
        },
        lessonsLearned: 'AMNS (ArcelorMittal) follows global procurement standards and values technical capability equally to price. SMPS power supply was a decisive differentiator — achieved 28% energy savings vs conventional TR sets. Quick commissioning (6 weeks) earned bonus for early completion.',
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'JSW Dolvi - Sinter Plant Head End ESP Upgrade',
        clientName: 'JSW Steel Limited - Dolvi Works',
        industry: 'pollution-control',
        year: 2025,
        bidderName: 'Our Company',
        isOurBid: true,
        flatGuarantee: 32000000,
        profitSharePct: 0,
        outcome: 'lost',
        winningBidSummary: 'Thermax won with comprehensive upgrade package including existing ESP retrofitting + new fields at INR 280 Crores. Their existing AMC relationship at Dolvi gave them insider advantage on the existing ESP condition assessment.',
        scoreReceived: 78.0,
        otherTerms: {
          our_price_inr_crores: 295,
          winner_price_inr_crores: 280,
          price_gap_pct: 5.4,
          our_technical_score: 48,
          winner_technical_score: 53,
          esp_capacity_m3_hr: 1350000,
        },
        lessonsLearned: 'For upgrade/retrofit projects, having existing AMC relationships is a massive advantage — competitor had detailed condition data we did not have. Need to pursue AMC contracts proactively as a gateway to future CAPEX orders. Thermax\'s in-house TR set manufacturing also gave them a cost advantage.',
        competitor: { connect: { id: competitors[13].id } },
      },
    }),

    // Competitor ESP bids
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Tata Steel Jamshedpur - Coke Oven Gas Cleaning ESP',
        clientName: 'Tata Steel Limited - Jamshedpur',
        industry: 'pollution-control',
        year: 2024,
        bidderName: 'Thermax Limited',
        isOurBid: false,
        flatGuarantee: 42000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 90.0,
        otherTerms: {
          esp_capacity_m3_hr: 2200000,
          outlet_emission_mg_nm3: 20,
          project_value_inr_crores: 380,
          delivery_months: 20,
        },
        lessonsLearned: 'Thermax won on technical superiority (90/100 overall) with their new-generation rigid frame electrode. Their in-house SMPS TR sets and 2000+ installation reference list was unmatched. They also offered 5-year AMC with performance guarantee.',
        competitor: { connect: { id: competitors[13].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'NTPC Singrauli - Boiler ESP (2 x 500 MW)',
        clientName: 'NTPC Limited - Singrauli',
        industry: 'pollution-control',
        year: 2025,
        bidderName: 'BHEL',
        isOurBid: false,
        flatGuarantee: 65000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 72.0,
        otherTerms: {
          esp_capacity_m3_hr: 3500000,
          outlet_emission_mg_nm3: 30,
          project_value_inr_crores: 520,
          delivery_months: 24,
          won_on_l1_basis: true,
        },
        lessonsLearned: 'BHEL won purely on L1 (lowest price) basis as per NTPC procurement policy. Their government PSU pricing is 15-20% below private players. Power sector ESP market is dominated by BHEL for government utilities.',
        competitor: { connect: { id: competitors[14].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'UltraTech Cement Aditya Birla - Kiln ESP',
        clientName: 'UltraTech Cement Limited - Rajashree Plant',
        industry: 'pollution-control',
        year: 2024,
        bidderName: 'FLSmidth',
        isOurBid: false,
        flatGuarantee: 15000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 92.0,
        otherTerms: {
          esp_capacity_m3_hr: 950000,
          outlet_emission_mg_nm3: 20,
          project_value_inr_crores: 165,
          energy_consumption_kwh_per_1000m3: 0.85,
          delivery_months: 16,
        },
        lessonsLearned: 'FLSmidth won on lowest energy consumption guarantee (0.85 kWh/1000m³ vs industry avg 1.5). Their EAC-2000 SMPS technology is market-leading for energy efficiency. Cement clients care heavily about operating cost due to 24x7 operation.',
        competitor: { connect: { id: competitors[15].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'RINL Vizag Steel - Sinter Plant ESP Replacement',
        clientName: 'Rashtriya Ispat Nigam Ltd - Vizag',
        industry: 'pollution-control',
        year: 2025,
        bidderName: 'Hamon India',
        isOurBid: false,
        flatGuarantee: 25000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 83.0,
        otherTerms: {
          esp_capacity_m3_hr: 1200000,
          outlet_emission_mg_nm3: 25,
          project_value_inr_crores: 210,
          delivery_months: 17,
          sinter_plant_esp_references: 12,
        },
        lessonsLearned: 'Hamon won on specialized sinter plant ESP experience (12 global references). Their patented rigid discharge electrode system is specifically designed for sticky sinter dust. Mid-range pricing and strong technical proposal gave best value score.',
        competitor: { connect: { id: competitors[16].id } },
      },
    }),
    prisma.historicalBid.create({
      data: {
        rfpTitle: 'Vedanta Jharsuguda - Smelter ESP',
        clientName: 'Vedanta Limited - Jharsuguda Aluminium',
        industry: 'pollution-control',
        year: 2024,
        bidderName: 'Unicon International',
        isOurBid: false,
        flatGuarantee: 12000000,
        profitSharePct: 0,
        outcome: 'won',
        scoreReceived: 80.0,
        otherTerms: {
          esp_capacity_m3_hr: 750000,
          outlet_emission_mg_nm3: 30,
          project_value_inr_crores: 98,
          delivery_months: 14,
          collecting_area_m2: 18000,
        },
        lessonsLearned: 'Unicon won on competitive pricing and quick delivery commitment (14 months vs 18-20 for others). Their Ahmedabad manufacturing facility allowed parallel fabrication. Aluminium smelter ESP requires fluoride-resistant materials — Unicon had relevant experience.',
        competitor: { connect: { id: competitors[18].id } },
      },
    }),
  ]);

  console.log(`Created ${historicalBids.length} historical bid records`);

  // ─── SAMPLE RFPS (pre-parsed) ───
  const rfp1 = await prisma.rfp.create({
    data: {
      title: 'Cochin International Airport - Advertising Media Rights 2026',
      clientName: 'Cochin International Airport Ltd (CIAL)',
      industry: 'airport',
      status: 'analyzed',
      projectScope: 'Exclusive rights to manage all advertising media across Cochin International Airport including Terminal 1, Terminal 2, domestic and international arrival/departure areas, duty-free zones, and parking facilities. Includes 200+ digital screens and 150+ static display positions.',
      submissionDeadline: new Date('2026-05-15'),
      contractDuration: '5 years with 2-year extension option',
      estimatedValue: 10000000,
      location: 'Kochi, Kerala, India',
      createdBy: user1.id,
    },
  });

  await prisma.scoringCriteria.createMany({
    data: [
      { rfpId: rfp1.id, criterionName: 'Financial Offer', maxPoints: 35, weightPct: 35, description: 'MAG amount, revenue share percentage, and annual escalation', sortOrder: 0, aiStrategy: 'Offer competitive MAG of $2.5-3M based on historical Cochin traffic data. Propose 13-15% revenue share to compensate. Include 5% annual escalation to show commitment.' },
      { rfpId: rfp1.id, criterionName: 'Experience & Track Record', maxPoints: 25, weightPct: 25, description: 'Airport advertising experience, similar contracts managed, client references', sortOrder: 1, aiStrategy: 'Highlight Mumbai and Chennai airport wins. Include specific ROI metrics from past campaigns. Provide 3+ client testimonials with measurable results.' },
      { rfpId: rfp1.id, criterionName: 'Technical Approach', maxPoints: 25, weightPct: 25, description: 'Digital innovation, inventory optimization, maintenance plan', sortOrder: 2, aiStrategy: 'Propose AI-driven content scheduling synced with flight data. Include AR/interactive advertising pilots. Present detailed maintenance SLA with 99.5% uptime guarantee.' },
      { rfpId: rfp1.id, criterionName: 'Team & Organization', maxPoints: 10, weightPct: 10, description: 'Key personnel, organizational capability, financial stability', sortOrder: 3 },
      { rfpId: rfp1.id, criterionName: 'Sustainability', maxPoints: 5, weightPct: 5, description: 'Green advertising initiatives, energy-efficient displays, CSR programs', sortOrder: 4 },
    ],
  });

  const rfp2 = await prisma.rfp.create({
    data: {
      title: 'Bangalore Metro Phase 3 - Civil Construction Package',
      clientName: 'Bangalore Metro Rail Corporation Ltd (BMRCL)',
      industry: 'construction',
      status: 'analyzed',
      projectScope: 'Design and construction of 12 elevated metro stations and 15km of elevated viaduct for Bangalore Metro Phase 3 (ORR Line). Includes station architecture, structural works, MEP systems, and integration with existing metro network.',
      submissionDeadline: new Date('2026-06-30'),
      contractDuration: '4 years construction + 2 years defect liability',
      estimatedValue: 75000000,
      location: 'Bangalore, Karnataka, India',
      createdBy: user1.id,
    },
  });

  await prisma.scoringCriteria.createMany({
    data: [
      { rfpId: rfp2.id, criterionName: 'Financial Bid', maxPoints: 40, weightPct: 40, description: 'Total project cost, payment schedule, cost breakdown', sortOrder: 0 },
      { rfpId: rfp2.id, criterionName: 'Technical Capability', maxPoints: 25, weightPct: 25, description: 'Construction methodology, equipment, quality management plan', sortOrder: 1 },
      { rfpId: rfp2.id, criterionName: 'Past Experience', maxPoints: 20, weightPct: 20, description: 'Similar metro/infrastructure projects, scale of past works', sortOrder: 2 },
      { rfpId: rfp2.id, criterionName: 'Project Timeline', maxPoints: 10, weightPct: 10, description: 'Construction schedule, milestone plan, risk mitigation', sortOrder: 3 },
      { rfpId: rfp2.id, criterionName: 'Safety & Environment', maxPoints: 5, weightPct: 5, description: 'Safety record, environmental management, dust/noise mitigation', sortOrder: 4 },
    ],
  });

  const rfp3 = await prisma.rfp.create({
    data: {
      title: 'Pan-India Warehouse Logistics Network - RFP 2026',
      clientName: 'Amazon India Pvt Ltd',
      industry: 'logistics',
      status: 'analyzed',
      projectScope: 'End-to-end management of 25 fulfillment centers across India including inbound logistics, inventory management, order processing, last-mile delivery coordination, and reverse logistics. Expected to handle 500K+ orders daily.',
      submissionDeadline: new Date('2026-04-30'),
      contractDuration: '3 years with annual renewal option',
      estimatedValue: 40000000,
      location: 'Pan-India (25 cities)',
      createdBy: user2.id,
    },
  });

  await prisma.scoringCriteria.createMany({
    data: [
      { rfpId: rfp3.id, criterionName: 'Operational Capability', maxPoints: 30, weightPct: 30, description: 'Warehouse management systems, automation level, throughput capacity', sortOrder: 0 },
      { rfpId: rfp3.id, criterionName: 'Cost Structure', maxPoints: 25, weightPct: 25, description: 'Per-unit handling cost, fixed vs variable cost model, volume discounts', sortOrder: 1 },
      { rfpId: rfp3.id, criterionName: 'Technology & Innovation', maxPoints: 20, weightPct: 20, description: 'WMS platform, real-time tracking, AI/ML capabilities, API integration', sortOrder: 2 },
      { rfpId: rfp3.id, criterionName: 'Scalability & Coverage', maxPoints: 15, weightPct: 15, description: 'Geographic coverage, ability to scale during peak seasons (10x), multi-city presence', sortOrder: 3 },
      { rfpId: rfp3.id, criterionName: 'SLA & Compliance', maxPoints: 10, weightPct: 10, description: 'Delivery SLAs, accuracy rates, regulatory compliance, insurance', sortOrder: 4 },
    ],
  });

  // ─── NEW SAMPLE RFPS ───
  const rfp4 = await prisma.rfp.create({
    data: {
      title: 'Apollo Hospitals - Digital Transformation & Patient Info System',
      clientName: 'Apollo Hospitals Enterprise Limited',
      industry: 'healthcare',
      status: 'analyzed',
      projectScope: 'Comprehensive digital transformation across 15 Apollo hospital facilities in South India. Includes 800+ digital displays, patient information systems, digital wayfinding kiosks, telemedicine infrastructure (50 rooms), health-awareness advertising network, HIS/EMR integration, and data analytics dashboards.',
      submissionDeadline: new Date('2026-05-20'),
      contractDuration: '5 years with 3-year extension option',
      estimatedValue: 10200000,
      location: 'South India (Chennai HQ)',
      createdBy: user2.id,
    },
  });

  await prisma.scoringCriteria.createMany({
    data: [
      { rfpId: rfp4.id, criterionName: 'Technical Solution', maxPoints: 30, weightPct: 30, description: 'System architecture, HIS/EMR integration, UI/UX, cybersecurity and DISHA compliance', sortOrder: 0, aiStrategy: 'Propose microservices architecture with HL7/FHIR integration layer. Demonstrate EMR integration with live demo. Highlight HIPAA and DISHA compliance certifications.' },
      { rfpId: rfp4.id, criterionName: 'Financial Proposal', maxPoints: 25, weightPct: 25, description: 'Total cost of ownership (5-year), revenue share model', sortOrder: 1, aiStrategy: 'Offer competitive TCO with phased payment aligned to milestones. Propose 8-10% advertising revenue share with Apollo. Include energy-efficient display cost savings.' },
      { rfpId: rfp4.id, criterionName: 'Experience & Track Record', maxPoints: 20, weightPct: 20, description: 'Healthcare IT experience, hospital deployments, client references', sortOrder: 2, aiStrategy: 'Highlight Fortis hospital win and any healthcare IT certifications. Include patient satisfaction metrics from past deployments.' },
      { rfpId: rfp4.id, criterionName: 'Implementation Plan', maxPoints: 15, weightPct: 15, description: 'Timeline, change management, training, risk mitigation', sortOrder: 3 },
      { rfpId: rfp4.id, criterionName: 'Support & Maintenance', maxPoints: 10, weightPct: 10, description: 'SLA commitments (99.9% uptime), response time, dedicated support team', sortOrder: 4 },
    ],
  });

  const rfp5 = await prisma.rfp.create({
    data: {
      title: 'Jaipur Smart City - ICCC & IoT Infrastructure',
      clientName: 'Jaipur Smart City Limited (JSCL)',
      industry: 'smart-city',
      status: 'analyzed',
      projectScope: 'Design, development, and operation of Integrated Command & Control Center (ICCC) with city-wide IoT deployment including 2,500 smart streetlights, 500 traffic cameras with AI, 200 air quality stations, 150 smart parking sensors, 100 water quality sensors, and citizen engagement platform. Includes 5-year O&M.',
      submissionDeadline: new Date('2026-05-10'),
      contractDuration: '2 years implementation + 5 years O&M',
      estimatedValue: 54000000,
      location: 'Jaipur, Rajasthan, India',
      createdBy: user1.id,
    },
  });

  await prisma.scoringCriteria.createMany({
    data: [
      { rfpId: rfp5.id, criterionName: 'Technical Solution', maxPoints: 35, weightPct: 35, description: 'ICCC architecture, IoT platform scalability, AI/ML analytics, cybersecurity', sortOrder: 0, aiStrategy: 'Propose cloud-native ICCC platform with open APIs. Highlight Indore ICCC success. Demonstrate AI-powered traffic and flood prediction capabilities.' },
      { rfpId: rfp5.id, criterionName: 'Financial Proposal', maxPoints: 30, weightPct: 30, description: 'Total CapEx + OpEx cost, revenue generation potential, value engineering', sortOrder: 1, aiStrategy: 'Offer competitive CapEx with O&M savings through predictive maintenance. Propose smart parking and advertising revenue model to offset costs.' },
      { rfpId: rfp5.id, criterionName: 'Experience & Credentials', maxPoints: 20, weightPct: 20, description: 'Smart city/ICCC project experience, government client references', sortOrder: 2 },
      { rfpId: rfp5.id, criterionName: 'Implementation Approach', maxPoints: 10, weightPct: 10, description: 'Project plan, risk management, local workforce development', sortOrder: 3 },
      { rfpId: rfp5.id, criterionName: 'Innovation & Sustainability', maxPoints: 5, weightPct: 5, description: 'Green technology, heritage conservation integration', sortOrder: 4 },
    ],
  });

  const rfp6 = await prisma.rfp.create({
    data: {
      title: 'GUVNL 750 MW Solar Park - EPC & O&M',
      clientName: 'Gujarat Urja Vikas Nigam Limited (GUVNL)',
      industry: 'renewable-energy',
      status: 'analyzed',
      projectScope: 'EPC of 750 MW solar PV park in Kutch with 1.5M bifacial modules, single-axis trackers, 150 central inverters, 5 pooling substations, 765 kV interconnection, 200 MWh BESS, and 50 km transmission line. Includes 25-year O&M with robotic cleaning and performance optimization.',
      submissionDeadline: new Date('2026-05-15'),
      contractDuration: '2 years EPC + 25 years O&M',
      estimatedValue: 540000000,
      location: 'Khavda, Kutch, Gujarat, India',
      createdBy: user1.id,
    },
  });

  await prisma.scoringCriteria.createMany({
    data: [
      { rfpId: rfp6.id, criterionName: 'Financial Bid', maxPoints: 40, weightPct: 40, description: 'EPC cost per MW, O&M NPV, tariff bid (LCOE), performance guarantee terms', sortOrder: 0, aiStrategy: 'Leverage Karnataka 400 MW project experience to offer competitive per-MW cost. Propose aggressive LCOE with BESS value-stacking. Include performance guarantee of 23.5% CUF.' },
      { rfpId: rfp6.id, criterionName: 'Technical Capability', maxPoints: 25, weightPct: 25, description: 'Solar technology, BESS design, electrical infrastructure, O&M automation', sortOrder: 1 },
      { rfpId: rfp6.id, criterionName: 'Experience & Track Record', maxPoints: 20, weightPct: 20, description: 'MW commissioned, similar terrain projects, CUF achievements', sortOrder: 2 },
      { rfpId: rfp6.id, criterionName: 'Project Execution Plan', maxPoints: 10, weightPct: 10, description: 'Construction timeline, supply chain, weather risk mitigation', sortOrder: 3 },
      { rfpId: rfp6.id, criterionName: 'Sustainability & Local Impact', maxPoints: 5, weightPct: 5, description: 'Local manufacturing, workforce development, environmental management', sortOrder: 4 },
    ],
  });

  const rfp7 = await prisma.rfp.create({
    data: {
      title: 'Reliance Retail - Integrated Facility Management (500 Stores)',
      clientName: 'Reliance Retail Limited',
      industry: 'retail',
      status: 'analyzed',
      projectScope: 'Comprehensive IFM services across 500 retail stores (Reliance Fresh, Digital, Trends) in Western/Southern India. Covers HVAC, electrical, plumbing, fire safety, housekeeping, pest control, waste management, IoT predictive maintenance, energy management, and CAFM platform deployment. Total area: 5M sq ft.',
      submissionDeadline: new Date('2026-05-25'),
      contractDuration: '5 years with 2-year extension option',
      estimatedValue: 14400000,
      location: 'Western & Southern India (6 states)',
      createdBy: user3.id,
    },
  });

  await prisma.scoringCriteria.createMany({
    data: [
      { rfpId: rfp7.id, criterionName: 'Commercial Proposal', maxPoints: 30, weightPct: 30, description: 'Per sq ft rate, energy savings guarantee, volume discounts, 5-year TCO', sortOrder: 0, aiStrategy: 'Offer tiered per-sq-ft pricing based on store format. Guarantee 15% energy savings with shared savings model. Propose aggressive volume discounts for portfolio expansion.' },
      { rfpId: rfp7.id, criterionName: 'Technical Capability', maxPoints: 25, weightPct: 25, description: 'CAFM platform, IoT capabilities, energy management approach, sustainability plan', sortOrder: 1, aiStrategy: 'Demonstrate CAFM platform with real-time SLA dashboards. Propose IoT sensors for HVAC predictive maintenance. Include ESG reporting module.' },
      { rfpId: rfp7.id, criterionName: 'Experience & Scale', maxPoints: 20, weightPct: 20, description: 'Retail FM experience, geographic coverage, client references', sortOrder: 2 },
      { rfpId: rfp7.id, criterionName: 'Operational Plan', maxPoints: 15, weightPct: 15, description: 'Transition plan, staffing model, supply chain for spares', sortOrder: 3 },
      { rfpId: rfp7.id, criterionName: 'Innovation & Value-Add', maxPoints: 10, weightPct: 10, description: 'Predictive maintenance, customer experience enhancement, ESG reporting', sortOrder: 4 },
    ],
  });

  const rfp8 = await prisma.rfp.create({
    data: {
      title: 'Visakhapatnam Port - Container Terminal & Logistics Management',
      clientName: 'Visakhapatnam Port Authority (VPA)',
      industry: 'port',
      status: 'draft',
      projectScope: 'Integrated management of container terminal (6 berths, 1.2M TEU capacity), 200,000 sqm warehousing, temperature-controlled storage, multimodal connectivity (rail + road), TOS implementation, and customs EDI interface at Visakhapatnam Port.',
      submissionDeadline: new Date('2026-04-25'),
      contractDuration: '10 years with 5-year extension option',
      estimatedValue: 96000000,
      location: 'Visakhapatnam, Andhra Pradesh, India',
      createdBy: user2.id,
    },
  });

  const rfp9 = await prisma.rfp.create({
    data: {
      title: 'Maharashtra State ERP System Implementation',
      clientName: 'Dept of IT, Government of Maharashtra',
      industry: 'government',
      status: 'draft',
      projectScope: 'Comprehensive ERP implementation across 35 government departments and 200+ district offices. Covers finance, HR/payroll (850K employees), procurement (GeM integration), asset management, project monitoring, citizen portal (150+ e-services), and BI dashboards. Cloud hosting on MeghRaj with DR setup.',
      submissionDeadline: new Date('2026-06-01'),
      contractDuration: '3 years implementation + 5 years AMC',
      estimatedValue: 78000000,
      location: 'Mumbai (HQ), Pan-Maharashtra',
      createdBy: user1.id,
    },
  });

  const rfp10 = await prisma.rfp.create({
    data: {
      title: 'IIT Madras - Campus Network & Digital Learning Platform',
      clientName: 'Indian Institute of Technology Madras',
      industry: 'education',
      status: 'draft',
      projectScope: 'Campus-wide network overhaul: 400 Gbps backbone, Wi-Fi 7 (4000+ APs across 200+ buildings), Tier-3 data center upgrade, SDN deployment, LMS for 800+ courses, 150 smart classrooms with lecture capture, virtual lab environment, AI student analytics, and next-gen security infrastructure.',
      submissionDeadline: new Date('2026-05-05'),
      contractDuration: '18 months implementation + 7 years AMC',
      estimatedValue: 14400000,
      location: 'Chennai, Tamil Nadu, India',
      createdBy: user3.id,
    },
  });

  // Link some competitors to RFPs
  await prisma.rfpCompetitor.createMany({
    data: [
      { rfpId: rfp1.id, competitorId: competitors[0].id, expectedStrategy: 'Will leverage existing GMR relationship and offer high MAG. Likely to propose $3M+ guarantee with premium service package.', threatLevel: 'high' },
      { rfpId: rfp1.id, competitorId: competitors[1].id, expectedStrategy: 'Will focus on digital innovation and AR experiences. May offer lower MAG but higher revenue share (15%+).', threatLevel: 'medium' },
      { rfpId: rfp1.id, competitorId: competitors[3].id, expectedStrategy: 'First bid in India. May offer aggressive terms to establish presence. Could bring international luxury brand commitments.', threatLevel: 'medium' },
      { rfpId: rfp2.id, competitorId: competitors[2].id, expectedStrategy: 'Will bid lowest price. Aggressive on cost, weak on technical and safety scores.', threatLevel: 'medium' },
      { rfpId: rfp2.id, competitorId: competitors[5].id, expectedStrategy: 'Strong government experience and safety record. Will bid conservatively with focus on quality and reliability.', threatLevel: 'high' },
      { rfpId: rfp2.id, competitorId: competitors[6].id, expectedStrategy: 'Will emphasize sustainable construction methods. May target the Safety & Environment criterion heavily.', threatLevel: 'low' },
      { rfpId: rfp3.id, competitorId: competitors[4].id, expectedStrategy: 'Strongest competitor with deep logistics expertise and AI optimization. Will likely win on operational capability.', threatLevel: 'high' },
      // New RFP competitor links
      { rfpId: rfp4.id, competitorId: competitors[7].id, expectedStrategy: 'Will propose SAP Health platform with 500+ consultant bench. Strong healthcare IT references from Max Healthcare and Rajasthan ERP wins.', threatLevel: 'high' },
      { rfpId: rfp4.id, competitorId: competitors[1].id, expectedStrategy: 'Will leverage AIIMS and Kerala telemedicine wins. Digital signage and content platform experience in hospitals is a strength.', threatLevel: 'medium' },
      { rfpId: rfp4.id, competitorId: competitors[12].id, expectedStrategy: 'May bid with Oracle Health Cloud platform. Scale and brand name will be their primary advantage. Likely premium pricing.', threatLevel: 'medium' },
      { rfpId: rfp5.id, competitorId: competitors[12].id, expectedStrategy: 'Strongest competitor with 8 ICCC projects. MeitY empanelment and NIC integration gives them procurement advantage.', threatLevel: 'high' },
      { rfpId: rfp5.id, competitorId: competitors[7].id, expectedStrategy: 'May bid as consortium partner for software platform. SAP-based ICCC solution could be compelling.', threatLevel: 'low' },
      { rfpId: rfp6.id, competitorId: competitors[9].id, expectedStrategy: 'Will bid lowest LCOE with in-house manufacturing. 2 GW+ track record and 24%+ CUF is hard to beat. Weak on BESS.', threatLevel: 'high' },
      { rfpId: rfp6.id, competitorId: competitors[6].id, expectedStrategy: 'Will target sustainability scores. Strong BESS expertise from Ladakh project. May consortium with module manufacturer.', threatLevel: 'medium' },
      { rfpId: rfp7.id, competitorId: competitors[8].id, expectedStrategy: 'Strongest competitor with 2000+ retail stores managed. Lowest per-sq-ft rates in market. CAFM platform advantage.', threatLevel: 'high' },
      { rfpId: rfp8.id, competitorId: competitors[10].id, expectedStrategy: 'Global port operator with proprietary TOS. Will benchmark against international terminals. Premium pricing.', threatLevel: 'high' },
      { rfpId: rfp8.id, competitorId: competitors[4].id, expectedStrategy: 'Will leverage Mundra Port win and logistics expertise. May underbid on license fee to win port management experience.', threatLevel: 'medium' },
      { rfpId: rfp9.id, competitorId: competitors[7].id, expectedStrategy: 'Won Rajasthan ERP. SAP platform and 500+ consultants. Strongest competitor for government ERP.', threatLevel: 'high' },
      { rfpId: rfp9.id, competitorId: competitors[12].id, expectedStrategy: 'MeitY empanelment and NIC experience. May propose Oracle/Microsoft cloud-based ERP.', threatLevel: 'high' },
      { rfpId: rfp10.id, competitorId: competitors[11].id, expectedStrategy: 'Deployed networks at IIT Delhi and IIT Bombay. Deep education sector expertise. Cisco Gold partner.', threatLevel: 'high' },
      { rfpId: rfp10.id, competitorId: competitors[12].id, expectedStrategy: 'May bid for the full project. Scale advantage but generic approach for education sector.', threatLevel: 'medium' },
    ],
  });

  console.log(`Created 10 sample RFPs with scoring criteria and competitor analysis`);

  console.log('\n✅ Seed completed successfully!');
  console.log('─────────────────────────────────');
  console.log('Users:');
  console.log('  demo@rfpai.com / demo123456 (Manager)');
  console.log('  suganya@rfpai.com / demo123456 (Analyst)');
  console.log('  sathish@rfpai.com / demo123456 (Analyst)');
  console.log(`Competitors: ${competitors.length}`);
  console.log(`Historical Bids: ${historicalBids.length}`);
  console.log(`Sample RFPs: 10 (7 analyzed + 3 draft, with scoring criteria and competitor analysis)`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
